### ISSUE TITLE
Switch WinSCP rule from SourceForge to the website

### ISSUE THREAD

**Issue by pgaskin** [just-install/just-install-updater-go#10]
The website is a lot more reliable, and fails less.

**Comment by lvillani** [comment]
Is SF's problem related to the fact that you often go to random mirror or is the site generally flakey?

**Comment by geek1011** [comment]
@lvillani It's just that sourceforge keeps making changes which break the updater no matter how general I try to make the rule. There's just no way to make the rule perfect.
