### ISSUE TITLE
Add support for 64-bit only entries

### ISSUE THREAD

**Issue by geek1011** [just-install/just-install-updater-go#15]
Support was recently added to just-install [here](https://github.com/just-install/just-install/commit/209aafe625e613eb750d625b66eb58719cf7d609).

- [x] Make 32-bit url and queries pointers
- [x] Update tests
- [x] Update rules

**Comment by cyagon** [comment]
@geek1011 if you could do this, i could update the rules then, if it helps

**Comment by geek1011** [comment]
@cyagon done
