### ISSUE TITLE
travis-ci.com

### ISSUE THREAD

**Issue by lvillani** [just-install/just-install-updater-go#37]
@geek1011 GitHub is deprecating the old services integration and telling users to switch to "GitHub Apps".

I "installed" Travis' GitHub App (travis-ci.com vs travis-ci.org) into our org and whitelisted some repositories.

Now I need to ask Travis' support to migrate these repos from `travis-ci.org` to `travis-ci.com` (this whole [migration](https://docs.travis-ci.com/user/open-source-on-travis-ci-com/) thing is a bit confusing, I may be getting something wrong).

Migration appears to be faster if we don't retain build history ([source](https://docs.travis-ci.com/user/open-source-on-travis-ci-com/#existing-open-source-repositories-on-travis-ciorg)).

Is it OK if I include jiup-go in the list of repos to migrate to their new infrastructure?

**Comment by geek1011** [comment]
Yep. I've been meaning to do this for a while, but never got around to it. I think I'll need to set GITHUB_TOKEN again after the migration.

**Comment by lvillani** [comment]
It should be done. I see `GITHUB_TOKEN` is there, the migration tool seems to have ported it over.

Did it have a cron job? The migration process doesn't transfer that.

**Comment by geek1011** [comment]
Yep. I've put the cron job back. Thanks!
