### ISSUE TITLE
Bot account

### ISSUE THREAD

**Issue by geek1011** [just-install/just-install-updater-go#5]
What do you want to name the bot account which will be used for updating the registry (#4)?

cc @just-install/owners @just-install/maintainers @just-install/registry

**Comment by geek1011** [comment]
Here's my ideas: jibot, just-install-bot

**Comment by cyagon** [comment]
just-install-bot sounds good

**Comment by geek1011** [comment]
I've created the account @just-install-bot

**Comment by geek1011** [comment]
I've finally got the deployment script working. Every day, it will be automatically ran by Travis CI.

All that's left is to finish the rest of the rules.
