### ISSUE TITLE
Distinguish between no rule and latest URL

### ISSUE THREAD

**Issue by mimi89999** [just-install/just-install-updater-go#55]
Hello,
The updater does not distinguish installers with no rule from installers with the URL pointing to the latest version in _RESULTS_. Because of that, it's more difficult to identify installers that are missing a rule.

**Comment by mimi89999** [comment]
@geek1011 Any thoughts on this? Can I go ahead and change that?

**Comment by geek1011** [comment]
How were you thinking of doing this?

**Comment by mimi89999** [comment]
I see 3 way of doing this:
1. Reading the registry file and interpreting the `latest` string in version
2. Hard coding a list of in the updater
3. Adding rules for those entries

**Comment by geek1011** [comment]
I think the first method is the best.

**Comment by mimi89999** [comment]
BTW, we are tracked by repology and I'm using https://repology.org/projects/?inrepo=just-install&outdated=1 to discover entries with missing rules.
