### ISSUE TITLE
Inconsistency in version placeholder location

### ISSUE THREAD

**Issue by mimi89999** [just-install/just-install-updater-go#56]
Hello,
I noticed that some installers have the `{{.version}}` placeholder in the URL in the registry and others have the `{{.Version}}` placeholder in the updater URL template. What's the reason for this?

**Comment by geek1011** [comment]
That's mainly due to historical reasons. Currently, we generally use the placeholder in the registry for manually updated entries, and the placeholder in the updater for automatically updated ones.
