### ISSUE TITLE
Use GitHub API to discover releases

### ISSUE THREAD

**Issue by mimi89999** [just-install/just-install-updater-go#84]
I think that it might be better to use GitHub API to discover releases (https://docs.github.com/en/rest/reference/repos#releases) than to regex through the GitHub page in https://github.com/just-install/just-install-updater-go/blob/master/jiup/rules/version/github.go.

**Comment by geek1011** [comment]
We originally were doing it that way, but we switched due to hitting rate limits. I guess we could put a GH token in (possibly from the bot account so we don't use up our own limits).

**Comment by mimi89999** [comment]
Is it possible to keep the token outside of the repo?

**Comment by geek1011** [comment]
Yes, it would be a secret defined on AppVeyor (or whatever).

**Comment by lvillani** [comment]
If regex work "well enough" I think we should keep using those. Using the API introduces another moving piece, more complex than a regex, that will _inevitably_ break.
